title: Блог о Genshin Impact
baseURL: /
params:
  palette: yellow
  header:
    title: Fjord
    tagline: Minimal and clean blog theme
    logo_img: images/logo.svg
    logo_img_alt: Fjord Logo
    background_img: images/incredible-coriander.jpg
    has_nav: true
    nav_links:
      - label: Главная
        url: /
        style: link
      - label: Гайды
        url: /about
        style: link
      - label: Мои контакты
        url: /contact
        style: link
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/'
        style: icon
        icon_class: twitter
        new_window: true
      - label: Instagram
        url: 'https://www.instagram.com/'
        style: icon
        icon_class: instagram
        new_window: true
      - label: GitHub
        url: 'https://github.com/'
        style: icon
        icon_class: github
        new_window: true
  footer: {}
  domain: 'https://pleasant-primrose-07863.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
