title: Блог о Genshin Impact
baseURL: /
params:
  palette: blue
  header:
    title: Genshin
    tagline: Блог о Genshin Impact. Гайды и прохождения
    logo_img: images/oceanic-steel.png
    logo_img_alt: Fjord Logo
    background_img: images/incredible-coriander.jpg
    has_nav: true
    nav_links:
      - label: Главная
        url: /
        style: link
      - label: Гайды
        url: /about
        style: link
      - label: Мои контакты
        url: /contact
        style: link
        type: action
        label: Новости
        url: /news
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/'
        style: icon
        icon_class: twitter
        new_window: true
      - label: Instagram
        url: 'https://www.instagram.com/'
        style: icon
        icon_class: instagram
        new_window: true
      - label: GitHub
        url: 'https://github.com/'
        style: icon
        icon_class: github
        new_window: true
      - label: YouTube
        url: 'https://youtube.com'
        style: icon
        icon_class: youtube
        new_window: true
        no_follow: false
        type: action
  footer: {}
  domain: 'https://pleasant-primrose-07863.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
